name: First demo workflow
on: 
  push:
    branches:
      - main
  issues:
    types: [opened, reopened]
    
  schedule:
    - cron: '11 11 * * 5'
  
  workflow_dispatch:
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - run:  "hello"
      
