name: First demo workflow
on: 
  push:
    branches:
      - main
    paths-ignore: [-github/*.*]
  pull_request:
    branches: [main]
    
  schedule:
    - cron: '15 6 * * 0'
  
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |  
          echo "The job was trigger by event: ${{ github.event_name }}"
          echo "The name of your brach is ${{ github.ref }}
      - uses: actions/checkout@v3.3.0
      - run: tree -a
